import DeleveSymbol from "./DeleveSymbol";
import { ArrowRight, Check, Pencil, Target, Trash2, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

type DailyFocus={text:string;completed:boolean};

export default function FocusOfDay(){
 const [focus,setFocus]=useState<DailyFocus>({text:"",completed:false});
 const [text,setText]=useState("");
 const [editing,setEditing]=useState(false);
 const [saving,setSaving]=useState(false);
 const [confirmingDelete,setConfirmingDelete]=useState(false);
 const [error,setError]=useState("");

 useEffect(()=>{fetch("/api/health/focus/today").then(response=>response.json()).then((body:{focus:DailyFocus|null})=>{setFocus(body.focus??{text:"",completed:false});setText(body.focus?.text??"")}).catch(()=>setError("Não foi possível carregar seu desafio de hoje."))},[]);

 async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/health/focus/today",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const body=await response.json().catch(()=>({})) as DailyFocus&{error?:string};if(!response.ok)throw new Error(body.error??"Não foi possível salvar seu desafio.");setFocus(body);setText(body.text);setEditing(false)}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível salvar seu desafio.")}finally{setSaving(false)}}
 async function toggle(){if(!focus)return;setSaving(true);setError("");try{const completed=!focus.completed;const response=await fetch("/api/health/focus/today",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({completed})});const body=await response.json().catch(()=>({})) as {completed:boolean;error?:string};if(!response.ok)throw new Error(body.error??"Não foi possível atualizar seu desafio.");setFocus({...focus,completed:body.completed})}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível atualizar seu desafio.")}finally{setSaving(false)}}
 async function remove(){setSaving(true);setError("");try{const response=await fetch("/api/health/focus/today",{method:"DELETE"});if(!response.ok)throw new Error();setFocus({text:"",completed:false});setText("");setEditing(false);setConfirmingDelete(false)}catch{setError("Não foi possível remover seu desafio.")}finally{setSaving(false)}}

 if(!focus.text&&!editing)return <button onClick={()=>setEditing(true)} className="group relative mt-4 w-full overflow-hidden rounded-[2rem] bg-gradient-to-br from-violet-600 via-fuchsia-500 to-orange-400 p-[1px] text-left shadow-xl shadow-fuchsia-900/10 outline-none transition hover:-translate-y-0.5 focus-visible:ring-4 focus-visible:ring-fuchsia-200"><span className="relative block overflow-hidden rounded-[calc(2rem-1px)] bg-[#17131f] p-5 text-white"><span className="absolute -right-8 -top-12 size-32 rounded-full bg-fuchsia-500/45 blur-2xl"/><span className="absolute -bottom-14 left-1/3 size-32 rounded-full bg-orange-400/25 blur-2xl"/><span className="relative flex items-center gap-3 sm:gap-4"><span className="grid size-10 shrink-0 place-items-center sm:size-12 rounded-2xl bg-white/10 text-fuchsia-200 ring-1 ring-white/15"><Target size={23}/></span><span className="min-w-0 flex-1"><span className="flex items-center gap-1.5 text-[.66rem] font-bold uppercase tracking-[.2em] text-fuchsia-200"><DeleveSymbol size={12} className="shrink-0"/>Meu desafio de hoje</span><strong className="mt-1 block text-lg tracking-tight">Escolha um pequeno passo.</strong></span><span className="grid size-8 shrink-0 place-items-center rounded-full bg-white sm:size-10 text-fuchsia-700 transition group-hover:translate-x-1"><ArrowRight size={18}/></span></span></span></button>;

 if(editing)return <section className="relative mt-4 overflow-hidden rounded-[2rem] bg-[#17131f] p-5 text-white shadow-xl shadow-fuchsia-900/10"><span className="absolute -right-10 -top-16 size-40 rounded-full bg-fuchsia-500/35 blur-3xl"/><div className="relative flex items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-fuchsia-500 to-orange-400 text-white"><Target size={21}/></span><div className="min-w-0"><p className="text-[.66rem] font-bold uppercase tracking-[.2em] text-fuchsia-200">Meu desafio de hoje</p><h3 className="font-bold">Escolha um desafio possível</h3></div><button type="button" aria-label="Cancelar edição" onClick={()=>{setEditing(false);setText(focus?.text??"");setError("")}} className="ml-auto grid size-9 shrink-0 place-items-center rounded-xl bg-white/10 text-white/70"><X size={17}/></button></div><form onSubmit={save} className="relative mt-4"><label className="sr-only" htmlFor="daily-focus">Seu desafio de hoje</label><textarea autoFocus id="daily-focus" required minLength={3} maxLength={100} rows={2} value={text} onChange={event=>setText(event.target.value)} placeholder="Ex.: Ir à academia" className="block w-full resize-none rounded-2xl border border-white/10 bg-white/10 p-4 text-lg font-bold text-white outline-none placeholder:font-normal placeholder:text-white/35 focus:border-fuchsia-300 focus:ring-4 focus:ring-fuchsia-400/20"/><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-white/45">{text.length}/100 · simples e possível</span><button disabled={saving||text.trim().length<3} className="flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-fuchsia-700 disabled:opacity-50">{saving?"Salvando...":"Salvar desafio"}<ArrowRight size={16}/></button></div>{error&&<p role="alert" className="mt-3 text-sm text-rose-300">{error}</p>}</form></section>;

 return <section className={`relative mt-4 overflow-hidden rounded-[2rem] p-6 text-white shadow-xl transition duration-500 md:p-5 ${focus.completed?"bg-gradient-to-br from-emerald-800 via-teal-700 to-cyan-600 shadow-emerald-900/10":"bg-gradient-to-br from-indigo-900 via-violet-700 to-rose-500 shadow-violet-900/10"}`}><span className="absolute -right-12 -top-12 size-44 rounded-full border border-white/12"/><span className="absolute -right-4 -top-2 size-28 rounded-full border border-white/10"/><span className="absolute -bottom-20 -left-12 size-48 rounded-full bg-white/8 blur-xl"/><div className="relative"><div className="flex items-center justify-between gap-3"><span className="flex min-w-0 items-center gap-2 text-[.68rem] font-bold uppercase tracking-[.22em] text-white/70"><DeleveSymbol size={13} className="shrink-0"/>Meu desafio de hoje</span><button aria-label="Editar desafio de hoje" onClick={()=>setEditing(true)} className="grid size-9 shrink-0 place-items-center rounded-xl bg-white/10 text-white/75 backdrop-blur"><Pencil size={16}/></button></div><p className="mt-7 max-w-[24ch] text-2xl font-bold leading-tight tracking-[-.035em] md:mt-4 md:text-xl">“{focus.text}”</p><div className="mt-6 flex items-center gap-3 md:mt-4"><button disabled={saving} onClick={toggle} aria-label={focus.completed?"Marcar desafio como pendente":"Concluir desafio"} className={`grid size-12 shrink-0 place-items-center rounded-full border-2 transition duration-300 md:size-10 ${focus.completed?"border-white bg-white text-emerald-700":"border-white/45 bg-white/10 text-transparent hover:border-white"}`}><Check size={23} strokeWidth={3}/></button><div><p className="text-sm font-bold">{focus.completed?"Desafio concluído":"Concluir desafio"}</p><p className="mt-0.5 text-xs text-white/65">{focus.completed?"Você conseguiu. Um passo de cada vez.":"Um passo de cada vez."}</p></div></div>{!confirmingDelete?<button onClick={()=>setConfirmingDelete(true)} className="mt-4 flex min-h-8 items-center gap-1.5 rounded-lg text-xs font-semibold text-white/45 hover:text-white md:mt-2"><Trash2 size={14}/>Remover desafio</button>:<div className="mt-4 flex flex-wrap items-center gap-2 rounded-xl bg-black/15 p-3 md:mt-2"><span className="text-xs text-white/80">Remover o desafio de hoje?</span><button onClick={()=>setConfirmingDelete(false)} className="min-h-9 rounded-lg bg-white/10 px-3 text-xs font-semibold">Cancelar</button><button disabled={saving} onClick={remove} className="min-h-9 rounded-lg bg-white px-3 text-xs font-bold text-rose-600">Remover</button></div>}{error&&<p role="alert" className="mt-3 text-sm text-rose-100">{error}</p>}</div></section>
}
