import { Check, UserRound, X } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { HealthProfile } from "./Dashboard";

const availableGoals=["Bem-estar geral","Perder peso","Ganhar peso","Manter peso","Dormir melhor","Beber mais água","Praticar atividade física"];

export default function ProfileDialog({open,profile,onClose,onSaved}:{open:boolean;profile:HealthProfile;onClose:()=>void;onSaved:(profile:HealthProfile)=>void}){
 const [name,setName]=useState("");
 const [height,setHeight]=useState("");
 const [goals,setGoals]=useState<string[]>([]);
 const [sleepGoalHours,setSleepGoalHours]=useState("8");
 const [waterGoalMl,setWaterGoalMl]=useState("2000");
 const [exerciseDaysWeek,setExerciseDaysWeek]=useState("3");
 const [targetWeightKg,setTargetWeightKg]=useState("");
 const [saving,setSaving]=useState(false),[error,setError]=useState("");

 useEffect(()=>{if(!open)return;setName(profile.name);setHeight(formatHeightFromCm(profile.heightCm));setGoals(profile.goals??profile.goal.split(",").map(item=>item.trim()));setSleepGoalHours(String(profile.sleepGoalHours||8));setWaterGoalMl(String(profile.waterGoalMl||2000));setExerciseDaysWeek(String(profile.exerciseDaysWeek||3));setTargetWeightKg(String(profile.targetWeightKg||""));setError("")},[open,profile]);
 if(!open)return null;

 function toggleGoal(goal:string){const weightGoals=["Perder peso","Ganhar peso","Manter peso"];setGoals(current=>current.includes(goal)?current.filter(item=>item!==goal):[...current.filter(item=>!weightGoals.includes(goal)||!weightGoals.includes(item)),goal])}
 async function save(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/health/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,heightCm:heightInCm(height),goals,sleepGoalHours,waterGoalMl,exerciseDaysWeek,targetWeightKg})});const body=await response.json().catch(()=>({})) as HealthProfile&{error?:string};if(!response.ok)throw new Error(body.error??"Não foi possível salvar o perfil.");onSaved(body);onClose()}catch(caught){setError(caught instanceof Error?caught.message:"Não foi possível salvar o perfil.")}finally{setSaving(false)}}

 return <div className="health-dialog-overlay fixed inset-0 z-50 bg-stone-950/45 p-0 backdrop-blur-sm sm:p-5"><section role="dialog" aria-modal="true" aria-labelledby="profile-title" className="health-dialog-panel w-full max-w-lg rounded-t-[2rem] bg-white p-6 shadow-2xl sm:rounded-[2rem] sm:p-7"><header className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-emerald-100 text-emerald-700"><UserRound size={21}/></span><div><p className="text-xs font-semibold text-emerald-700">Seu espaço</p><h2 id="profile-title" className="text-xl font-bold">Perfil e metas</h2></div></div><button type="button" onClick={onClose} aria-label="Fechar perfil" className="grid size-10 place-items-center rounded-xl bg-stone-100 text-stone-600"><X size={19}/></button></header><form onSubmit={save} className="mt-6"><TextField label="Como podemos chamar você?" value={name} onChange={setName}/><TextField label="Altura em metros" value={height} onChange={value=>setHeight(formatHeight(value))} inputMode="decimal"/><fieldset className="mt-6"><legend className="text-sm font-bold text-stone-700">Seus objetivos</legend><div className="mt-3 grid gap-2">{availableGoals.map(goal=><button key={goal} type="button" onClick={()=>toggleGoal(goal)} className={`flex min-h-12 items-center justify-between rounded-2xl border px-4 text-left text-sm font-semibold ${goals.includes(goal)?"border-emerald-500 bg-emerald-50 text-emerald-800":"border-stone-200 bg-stone-50 text-stone-600"}`}><span>{goal}</span>{goals.includes(goal)&&<Check size={17}/>}</button>)}</div></fieldset>{goals.includes("Dormir melhor")&&<NumberField label="Meta de sono" value={sleepGoalHours} onChange={setSleepGoalHours} unit="horas" min="4" max="12"/>}{goals.includes("Beber mais água")&&<NumberField label="Meta diária de água" value={waterGoalMl} onChange={setWaterGoalMl} unit="ml" min="500" max="6000"/>}{goals.includes("Praticar atividade física")&&<NumberField label="Exercícios por semana" value={exerciseDaysWeek} onChange={setExerciseDaysWeek} unit="dias" min="1" max="7"/>}{(goals.includes("Perder peso")||goals.includes("Ganhar peso"))&&<NumberField label="Peso desejado" value={targetWeightKg} onChange={setTargetWeightKg} unit="kg" min="20" max="400" step="0.1"/>}{error&&<p role="alert" className="mt-4 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}<button disabled={saving||!name||!height||!goals.length} className="mt-6 min-h-14 w-full rounded-2xl bg-emerald-700 px-5 font-bold text-white disabled:opacity-50">{saving?"Salvando...":"Salvar alterações"}</button></form></section></div>
}

function TextField({label,value,onChange,inputMode}:{label:string;value:string;onChange:(value:string)=>void;inputMode?:"decimal"}){return <label className="mt-4 block text-sm font-bold text-stone-700">{label}<input required inputMode={inputMode} value={value} onChange={event=>onChange(event.target.value)} className="mt-2 block h-14 w-full rounded-2xl border border-stone-200 bg-stone-50 px-4 text-base outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100"/></label>}
function NumberField({label,value,onChange,unit,min,max,step}:{label:string;value:string;onChange:(value:string)=>void;unit:string;min:string;max:string;step?:string}){return <label className="mt-5 block text-sm font-bold text-stone-700">{label}<span className="mt-2 flex h-14 items-center rounded-2xl border border-stone-200 bg-stone-50 px-4 focus-within:border-emerald-500 focus-within:ring-4 focus-within:ring-emerald-100"><input required type="number" min={min} max={max} step={step} value={value} onChange={event=>onChange(event.target.value)} className="min-w-0 flex-1 bg-transparent text-base font-bold outline-none"/><span className="text-sm text-stone-400">{unit}</span></span></label>}
function formatHeight(value:string){const digits=value.replace(/\D/g,"").slice(0,3);return digits.length<=1?digits:`${digits[0]},${digits.slice(1)}`}
function formatHeightFromCm(value:string){const cm=Math.round(Number(value));return Number.isFinite(cm)?formatHeight(String(cm)):""}
function heightInCm(value:string){return Math.round(Number(value.replace(",","."))*100)}
